# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ""
email: 
description: Personal and technical blog of Amielle
baseurl: "/" # the subpath of your site, e.g. /blog
url: "amielle.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: no
